DATASET:
  root_dataset: 'Dataset/chips'
  train_json: 'Dataset/chips/training.json'
  val_json: 'Dataset/chips/validation.json'

AUG:
  perform_augs: True
  perform_aug_proba: 0.5
  gaussian_blur_proba: 0.8
  color_jitter_proba: 0.8
  grid_distort_proba: 0.8 
  guass_noise_proba: 0.8

MODEL:
  model_arch: 'unetplusplus'                  #use only unetplusplus, manet, panet, deeplabv3plus
  encoder_name: 'resnet34'            #resnet 
  in_channels: 3
  classes: 3
  encoder_weights: None
  
TRAIN:
  batch_size: 1
  shuffle: True
  num_workers: 16
  class_weights: [1,1,3]
  lr: 2e-3
  scheduler_patience: 2
  lr_reduce_factor: 0.01
  init_ckpt: None
  wandb_iters: 2
  n_epochs: 1
  wandb_project_name: 'Guava'
  save_ckpt_dir: 'ckpts'
  mean_values: [0.5924760223571813, 0.6095723768544002, 0.4908530449121363]
  std_values: [0.13440405402135033, 0.12584898251577034, 0.2270173717238626]

VAL:
  batch_size: 1
  shuffle: False
  num_workers: 16